config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :collections, only: [:index, :show]
  
  resources :products, only: [:index, :show]
  
  resources :cart_items, only: [:destroy]
  
  resource :checkout, only: [:show] do
    post 'add_to_cart'
    get 'billing'
    put 'update_billing'
    get 'review'
    post 'submit_order'
  end
  
  match "/admin" => "admin/site#index", via: [:get], :as => "admin"

  root to: "site#index"
  
  namespace :admin do
    
    resources :discounts, only: [:index] do
      collection do
        patch 'apply'
      end
    end
    
    resources :colors, only: [:create]
    resources :vendors, only: [:create]
    resources :materials, only: [:create]
    resources :shapes, only: [:create]
    
    resources :coupons
    
    resources :collections do
      member do
        post 'add_products'
        delete 'remove_products'
        get 'search_products'
        get 'reset_search'
      end
    end
    
    resources :orders, only: [:index, :show, :update] do
      collection do
        get 'export'
      end
    end
    
    resources :file_uploads, only: [:index] do
      collection do
        post 'update_taxes'
      end
    end
    
    resources :variants, only: [] do
      collection do
        delete 'remove'
      end
    end
    
    resources :products do
      collection do
        get 'generate_variants'
        get 'add_color'
        get 'add_size'
        get 'add_image'
        get 'add_variant'
      end
    end
    
    resources :products_colors, only: [] do
      collection do
        put 'update_mens_sort_order'
        put 'update_womens_sort_order'
        delete 'remove'
      end
    end
    
    resources :product_images, only: [:destroy] do
      collection do
        put 'update_sort_order'
      end
    end
    
    resources :categories
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  
  INCOMPLETE = 'Incomplete'
  IN_PROGRESS = 'In progress'
  SHIPPED = 'Shipped'
  
  belongs_to :coupon
  belongs_to :user
  has_one :shipping_address, dependent: :destroy
  has_one :billing_address, dependent: :destroy
  
  has_many :line_items
  
  monetize :savings_cents
  monetize :total_cents
  monetize :tax_cents
  monetize :subtotal_cents
  monetize :shipping_cents
  
  def attach_coupon!(coupon)
    update_attributes!(coupon_id: coupon.id)
  end
  
  def self.status_options
    [Order::IN_PROGRESS, Order::SHIPPED]
  end
  
  def update_all_fees!
    #it must be in this order
    calculate_subtotal
    calculate_shipping
    calculate_coupon_discount
    calculate_tax
    calculate_total
    save!
  end
  
  def finalize!
    user.cart.cart_items.each do |cart_item|
      line_item = LineItem.new(cart_item.attributes.except("id", "cart_id"))
      line_item.unit_price = cart_item.variant.price
      line_item.order_id = self.id
      self.line_items << line_item
    end
    OrderMailer.confirmation_email(self).deliver
    set_status_to_in_progress
    set_order_date_to_today
    save
    user.cart.empty!
  end
  
  def set_order_date_to_today
    self.order_date = Date.today
  end
  
  def set_status_to_in_progress
    self.update_attributes!(status: IN_PROGRESS)
  end
  
  def calculate_subtotal
    self.subtotal = user.cart.total
  end
  
  def calculate_shipping
    0
  end
  
  def calculate_coupon_discount
    coupon.apply_discount(self) if coupon
  end
  
  def calculate_tax
    if self.shipping_address.state && self.shipping_address.state == State.new_york
      corresponding_tax = Tax.find_by(zip_code: self.shipping_address.zip_code, state_id: self.shipping_address.state_id)
      self.tax = corresponding_tax.rate * (self.subtotal + shipping)
    else
      self.tax = 0.00
    end
  end
  
  def calculate_total
    self.total = self.subtotal + self.shipping + self.tax - self.savings
  end
  
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  
  def index
    @orders = Order.where(status: [Order::IN_PROGRESS, Order::SHIPPED]).order("order_date ASC").paginate(page: params[:page], per_page: 30)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(order_params)
      redirect_to admin_order_path(@order), notice: "Order ##{@order.id} has been updated."
    else
      render 'show'
    end
  end
  
  def export
    from_date = params[:from_date].blank? ? Date.strptime("01/01/2014", '%m/%d/%Y') : Date.strptime(params[:from_date], '%m/%d/%Y')
    to_date = params[:to_date].blank? ? Date.today : Date.strptime(params[:to_date], '%m/%d/%Y')
    data = CsvGenerator.orders_report(from_date, to_date)
    send_data(data, filename: "orders_report_from_#{from_date}_to_#{to_date}.csv", type: 'text/csv')
  end
  
  private
  
    def order_params
      params.require(:order).permit(:status)
    end
  
end

app/views/admin/orders/index.html.erb
<h1>Orders</h1>
<%= form_tag export_admin_orders_path, method: :get do %>
	<%= text_field_tag "from_date", nil, class: "datepicker" %> to 
	<%= text_field_tag "to_date", nil, class: "datepicker" %>
	<%= submit_tag "Download Report" %>
<% end %>

<%= will_paginate @orders %>
<table>
	<thead>
<th>ID</th>
<th>Order Date</th>
<th>Status</th>
<th>Email</th>
<th>Total</th>
</thead>
<% @orders.each do |order| %>
<tr>

	<td><%= link_to order.id, admin_order_path(order) %></td>
	<td><%= order.order_date.try(:strftime, "%m/%d/%Y") %></td>
	<td><%= order.status %></td>
	<td><%= order.user.guest? ? order.user.guest_email : order.user.email %></td>
	<td><%= humanized_money_with_symbol order.total %></td>

</tr>
<% end %>
</table>

app/views/admin/orders/show.html.erb
<%= link_to "All Orders", admin_orders_path %>

<h3>Order Info</h3>

<%= form_for [:admin, @order] do |form| %>
	<%= form.collection_select :status, Order.status_options, :to_s, :to_s %>
	<%= form.submit "Update" %>
<% end %>

<div>Email: <%= @order.user.registered_email %></div>
<div>Order Date: <%= @order.order_date.try(:strftime, "%m/%d/%Y") %></div>
<div>Subtotal: <%= humanized_money_with_symbol @order.subtotal %></div>
<div>Shipping: <%= humanized_money_with_symbol @order.shipping %></div>
<div>Tax: <%= humanized_money_with_symbol @order.tax %></div>
<div>Total: <%= humanized_money_with_symbol @order.total %></div>

<h3>Line Items</h3>
<% @order.line_items.each do |line_item| %>
<div>Product: <%= line_item.variant.product.name %></div>
<div>Color: <%= line_item.variant.products_color.color.name %></div>
<div>Size: <%= line_item.variant.size.name %></div>
<div>SKU: <%= line_item.variant.sku %></div>
<div>Unit Price: <%= humanized_money_with_symbol line_item.unit_price %></div>
<div>Quantity: <%= line_item.quantity %></div><br>
<% end %>

<h3>Shipping Address</h3>
<div>First Name: <%= @order.shipping_address.first_name %></div>
<div>Last Name: <%= @order.shipping_address.last_name %></div>
<div>Street Address: <%= @order.shipping_address.street_address %></div>
<div>Apt/Suite: <%= @order.shipping_address.street_address2 %></div>
<div>City: <%= @order.shipping_address.city %></div>
<div>State: <%= @order.shipping_address.state.short_name %></div>
<div>Zip Code: <%= @order.shipping_address.zip_code %></div>
<div>Phone Number: <%= @order.shipping_address.phone_number %></div>

<h3>Billing Address</h3>
<div>First Name: <%= @order.billing_address.first_name %></div>
<div>Last Name: <%= @order.billing_address.last_name %></div>
<div>Street Address: <%= @order.billing_address.street_address %></div>
<div>Apt/Suite: <%= @order.billing_address.street_address2 %></div>
<div>City: <%= @order.billing_address.city %></div>
<div>State: <%= @order.billing_address.state.short_name %></div>
<div>Zip Code: <%= @order.billing_address.zip_code %></div>
<div>Phone Number: <%= @order.billing_address.phone_number %></div>