config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :collections, only: [:index, :show]
  
  resources :products, only: [:index, :show]
  
  resources :cart_items, only: [:destroy]
  
  resource :checkout, only: [:show] do
    post 'add_to_cart'
    get 'billing'
    put 'update_billing'
    get 'review'
    post 'submit_order'
  end
  
  match "/admin" => "admin/site#index", via: [:get], :as => "admin"

  root to: "site#index"
  
  namespace :admin do
    
    resources :discounts, only: [:index] do
      collection do
        patch 'apply'
      end
    end
    
    resources :colors, only: [:create]
    resources :vendors, only: [:create]
    resources :materials, only: [:create]
    resources :shapes, only: [:create]
    
    resources :coupons
    
    resources :collections do
      member do
        post 'add_products'
        delete 'remove_products'
        get 'search_products'
        get 'reset_search'
      end
    end
    
    resources :orders, only: [:index, :show, :update] do
      collection do
        get 'export'
      end
    end
    
    resources :file_uploads, only: [:index] do
      collection do
        post 'update_taxes'
      end
    end
    
    resources :variants, only: [] do
      collection do
        delete 'remove'
      end
    end
    
    resources :products do
      collection do
        get 'generate_variants'
        get 'add_color'
        get 'add_size'
        get 'add_image'
        get 'add_variant'
      end
    end
    
    resources :products_colors, only: [] do
      collection do
        put 'update_mens_sort_order'
        put 'update_womens_sort_order'
        delete 'remove'
      end
    end
    
    resources :product_images, only: [:destroy] do
      collection do
        put 'update_sort_order'
      end
    end
    
    resources :categories
  end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  
  before_filter :prevent_cache, only: [:billing]
  
  def add_to_cart
    @cart = current_or_guest_user.cart
    @cart.add_item!(params[:variant_id], params[:quantity])
    respond_to do |format|
      format.html { redirect_to checkout_path }
    end
  end
  
  def show
  end
  
  def billing
    @order = current_or_guest_user.last_incomplete_order
    @site_wide_coupon = Coupon.active.site_wide.last
    if current_user
      @payment_info = PaymentInfo.new(
                                  shipping_address_first_name: @order.shipping_address.try(:first_name),
                                  shipping_address_last_name: @order.shipping_address.try(:last_name),
                                  shipping_address_street_address: @order.shipping_address.try(:street_address),
                                  shipping_address_street_address2: @order.shipping_address.try(:street_address2),
                                  shipping_address_zip_code: @order.shipping_address.try(:zip_code),
                                  shipping_address_city: @order.shipping_address.try(:city),
                                  shipping_address_state_id: @order.shipping_address.try(:state_id),
                                  shipping_address_phone_number: @order.shipping_address.try(:phone_number),
                                  billing_address_first_name: @order.billing_address.try(:first_name),
                                  billing_address_last_name: @order.billing_address.try(:last_name),
                                  billing_address_street_address: @order.billing_address.try(:street_address),
                                  billing_address_street_address2: @order.billing_address.try(:street_address2),
                                  billing_address_zip_code: @order.billing_address.try(:zip_code),
                                  billing_address_city: @order.billing_address.try(:city),
                                  billing_address_state_id: @order.billing_address.try(:state_id),
                                  billing_address_phone_number: @order.billing_address.try(:phone_number),
                                  order_id: @order.id
                                  )
    else
      @payment_info = PaymentInfo.new(order_id: @order.id)
    end
  end
  
  def update_billing
    @order = current_or_guest_user.last_incomplete_order
    @payment_info = PaymentInfo.new(params[:payment_info].merge(order_id: @order.id))
    @payment_info.save
    respond_to do |format|
      format.js
    end
  end
  
  def submit_order
    @usaepay = UsaepayWrapper.new(params[:credit_card])
    if @usaepay.authorize
      order = current_or_guest_user.last_incomplete_order
      order.finalize!
      delete_sensitive_session_variables!
      render js: "window.location = '#{review_checkout_path}'"
    else
      respond_to do |format|
        format.js
      end
    end
  end
  
  def review
  end
  
  private
  
    def delete_sensitive_session_variables!
      cookies.delete(:guest_user_id)
    end

  
end

app/views/checkouts/_order_fees.html.erb
<div>
	Subtotal: <%= humanized_money_with_symbol order.subtotal %>
</div>
<div>
	Shipping: <%= humanized_money_with_symbol order.shipping %>
</div>
<% unless order.savings == 0 %>
<div>
	Savings: <%= humanized_money_with_symbol order.savings %>
</div>
<% end %>
<div>
	Tax: <%= humanized_money_with_symbol order.tax %>
</div>
<div>
	Total: <%= humanized_money_with_symbol order.total %>
</div>

app/views/checkouts/billing.html.erb
<%= form_for @payment_info, url: update_billing_checkout_path, remote: true, method: :put do |f| %>
	<ul class="payment_info_errors">
	<% @payment_info.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	
	<div class="payment_info_first_part">
	<% unless current_user %>
	<h3>User Information</h3>
	<div>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>		
	
	<div>
		<%= f.label :create_an_account %>
		<%= f.check_box :create_an_account %>
	</div>
	
	<div class="payment_info_password_fields">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<% end %>
	
	<h3>Shipping Address</h3>
	<div>
	<%= f.label :shipping_address_first_name, "First Name" %>
	<%= f.text_field :shipping_address_first_name %>
	</div>
	<div>
	<%= f.label :shipping_address_last_name, "Last Name" %>
	<%= f.text_field :shipping_address_last_name %>
	</div>
	<div>
	<%= f.label :shipping_address_street_address, "Street Address" %>
	<%= f.text_field :shipping_address_street_address %>
	</div>
	<div>
	<%= f.label :shipping_address_street_address2, "Apt/Suite" %>
	<%= f.text_field :shipping_address_street_address2 %>
	</div>
	<div>
	<%= f.label :shipping_address_city, "City" %>
	<%= f.text_field :shipping_address_city %>
	</div>
	<div>
	<%= f.label :shipping_address_state_id, "State" %>
	<%= f.collection_select :shipping_address_state_id, State.all, :id, :short_name %>
	</div>
	<div>
	<%= f.label :shipping_address_zip_code, "Zip Code" %>
	<%= f.text_field :shipping_address_zip_code %>
	</div>
	<div>
	<%= f.label :shipping_address_phone_number, "Phone Number" %>
	<%= f.text_field :shipping_address_phone_number %>
	</div>
	
	
	<h3>Billing Address</h3>
	<div>
	<%= f.label :billing_address_first_name, "First Name" %>
	<%= f.text_field :billing_address_first_name %>
	</div>
	<div>
	<%= f.label :billing_address_last_name, "Last Name" %>
	<%= f.text_field :billing_address_last_name %>
	</div>
	<div>
	<%= f.label :billing_address_street_address, "Street Address" %>
	<%= f.text_field :billing_address_street_address %>
	</div>
	<div>
	<%= f.label :billing_address_street_address2, "Apt/Suite" %>
	<%= f.text_field :billing_address_street_address2 %>
	</div>
	<div>
	<%= f.label :billing_address_city, "City" %>
	<%= f.text_field :billing_address_city %>
	</div>
	<div>
	<%= f.label :billing_address_state_id, "State" %>
	<%= f.collection_select :billing_address_state_id, State.all, :id, :short_name %>
	</div>
	<div>
	<%= f.label :billing_address_zip_code, "Zip Code" %>
	<%= f.text_field :billing_address_zip_code %>
	</div>
	<div>
	<%= f.label :billing_address_phone_number, "Phone Number" %>
	<%= f.text_field :billing_address_phone_number %>
	</div>
	
	<h3>Credit Card</h3>
	<div>
	<%= f.label :credit_card_number, "Card Number" %>
	<%= f.text_field :credit_card_number, autocomplete: 'off' %>
	</div>
	<div>
	<%= f.label :credit_card_exp_mm, "Expiration Date" %>
	<%= select_month((f.object.credit_card_exp_mm.try(:to_i) || Date.today), {use_two_digit_numbers: true}, name: "payment_info[credit_card_exp_mm]" ) %>
	<%= select_year((f.object.credit_card_exp_yyyy.try(:to_i) || Date.today), {}, start_year: Date.today.year, end_year: Date.today.year+10, name: "payment_info[credit_card_exp_yyyy]" )%>
	</div>
	<div>
	<%= f.label :credit_card_cvv, "CVV" %>
	<%= f.text_field :credit_card_cvv, autocomplete: 'off', value: '' %>
	</div>
	
	<h3>Coupon</h3>
	<div>
		<%= f.label :coupon_code %>
		<% if @site_wide_coupon && order_qualifies_for_coupon?(@order, @site_wide_coupon) %>
			<%= f.text_field :coupon_code, autocomplete: 'off', value: @site_wide_coupon.code %>
		<% else %>
			<%= f.text_field :coupon_code, autocomplete: 'off' %>
		<% end %>
	</div>
	
	<%= f.submit "Review" %>
	</div>

<% end %>



<div class="payment_info_second_part">
<%= submit_tag "Edit", id: "edit_payment_info_button" %>

<%= form_tag submit_order_checkout_path, remote: true do %>
<%= hidden_field_tag "credit_card[order_id]", @payment_info.order.id %>
<% @payment_info.user.cart.cart_items.each do |cart_item| %>
	<div>
		Product Name: <%= cart_item.variant.product.name %>
		Size: <%= cart_item.variant.size.name %>
		Quantity: <%= cart_item.quantity %>
		Price: <%= humanized_money_with_symbol(cart_item.variant.price) %>
	</div>
	
<% end %>

<div class="order_fees_div">
</div>

<div class="credit_card_inputs">
</div>
<%= submit_tag "Submit Order", id: "submit_order_button" %>
<% end %>

app/views/checkouts/review.html.erb
<h3>
	Thank you for your ordering at iLook
	<%= link_to "Continue Shopping", products_path %>
</h3>

app/views/checkouts/show.html.erb
<% current_or_guest_user.cart.cart_items.each do |cart_item| %>
	<div class="cart_item_<%= cart_item.id %>">
		Product Name: <%= cart_item.variant.product.name %> | 
		Size: <%= cart_item.variant.size.name %> | 
		Color: <%= cart_item.variant.products_color.color.name %> | 
		Quantity: <%= cart_item.quantity %> | 
		Price: <%= humanized_money_with_symbol(cart_item.variant.price) %> | 
		<%= link_to "X", cart_item_path(cart_item), method: :delete %>
	</div>
<% end %>

<% if current_or_guest_user.cart.cart_items.present? %>
	<%= link_to "Checkout", billing_checkout_path %>
<% else %>
	<%= link_to "Continue Shopping", products_path %>
<% end %>

app/views/checkouts/submit_order.js.erb
$(".payment_info_first_part :input").attr("disabled", false);
$(".payment_info_second_part :input").attr("disabled", true);

$(".payment_info_errors").empty();
$(".payment_info_errors").append("<li><%= @usaepay.result %></li>");
$(".payment_info_errors").append("<li><%= @usaepay.error %></li>");

jQuery('html,body').animate({scrollTop:0},300);

app/views/checkouts/update_billing.js.erb
<% if @payment_info.errors.present? %>
	$(".payment_info_errors").empty();
	<% @payment_info.errors.full_messages.each do |error_message| %>
		$(".payment_info_errors").append("<li><%= error_message %></li>");
	<% end %>	
	jQuery('html,body').animate({scrollTop:0},300);
<% else %>
	$(".payment_info_errors").empty();
	$(".payment_info_first_part :input").attr("disabled", true);
	$(".payment_info_second_part :input").attr("disabled", false);
	$(".order_fees_div").html("<%=j render partial: 'order_fees', locals: {order: @payment_info.order} %>");
<% end %>