config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :collections, only: [:index, :show]
  
  resources :products, only: [:index, :show]
  
  resources :cart_items, only: [:destroy]
  
  resource :checkout, only: [:show] do
    post 'add_to_cart'
    get 'billing'
    put 'update_billing'
    get 'review'
    post 'submit_order'
  end
  
  match "/admin" => "admin/site#index", via: [:get], :as => "admin"

  root to: "site#index"
  
  namespace :admin do
    
    resources :discounts, only: [:index] do
      collection do
        patch 'apply'
      end
    end
    
    resources :colors, only: [:create]
    resources :vendors, only: [:create]
    resources :materials, only: [:create]
    resources :shapes, only: [:create]
    
    resources :coupons
    
    resources :collections do
      member do
        post 'add_products'
        delete 'remove_products'
        get 'search_products'
        get 'reset_search'
      end
    end
    
    resources :orders, only: [:index, :show, :update] do
      collection do
        get 'export'
      end
    end
    
    resources :file_uploads, only: [:index] do
      collection do
        post 'update_taxes'
      end
    end
    
    resources :variants, only: [] do
      collection do
        delete 'remove'
      end
    end
    
    resources :products do
      collection do
        get 'generate_variants'
        get 'add_color'
        get 'add_size'
        get 'add_image'
        get 'add_variant'
      end
    end
    
    resources :products_colors, only: [] do
      collection do
        put 'update_mens_sort_order'
        put 'update_womens_sort_order'
        delete 'remove'
      end
    end
    
    resources :product_images, only: [:destroy] do
      collection do
        put 'update_sort_order'
      end
    end
    
    resources :categories
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  default_scope { order('name ASC') }
  
  has_many :collections_products
  has_many :products, -> { order 'products.name' }, through: :collections_products
  
  scope :active, -> { where(active: true) }
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::BaseController
  
  def new
    @collection = Collection.new
  end
  
  def index
    @collections = Collection.all.paginate(page: params[:page], per_page: 30)
  end
  
  def manage_products
    @collection = Collection.find(params[:id])
  end
  
  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      redirect_to edit_admin_collection_path(@collection), notice: "Your collection was successfully created."
    else
      render 'new'
    end
  end
  
  def edit
    @collection = Collection.find(params[:id])
    @search = Product.search(params[:q])
    @products = @search.result.order('name ASC').paginate(:page => params[:page], :per_page => 10)
  end
  
  def update
    @collection = Collection.find(params[:id])
    if @collection.update_attributes(collection_params)
      redirect_to edit_admin_collection_path(@collection), notice: "Your collection was successfully updated."
    else
      render 'edit'
    end
  end
  
  def add_products
    return unless params[:product_ids].present?
    @collection = Collection.find(params[:id])
    params[:product_ids].each do |product_id|
      product = Product.find(product_id)
      @collection.products << product unless @collection.products.include?(product)
    end
    respond_to do |format|
      format.js
    end
  end
  
  def remove_products
    return unless params[:product_ids].present?
    @collection = Collection.find(params[:id])
    params[:product_ids].each do |product_id|
      association = CollectionsProduct.find_by(product_id: product_id, collection_id: @collection.id)
      association.destroy
    end
    respond_to do |format|
      format.js
    end
  end
  
  def search_products
    @collection = Collection.find(params[:id])
    @products = Product.where("name LIKE ?", "%#{params[:search_term]}%")
    respond_to do |format|
      format.js
    end
  end
  
  def reset_search
    @collection = Collection.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    redirect_to admin_collections_path, notice: "Your collection was successfully deleted."
  end
  
  private
  
    def collection_params
      params.require(:collection).permit(:name, :short_description, :long_description, :active)
    end
  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  
  def show
    @collection = Collection.find(params[:id])
  end
  
  def index
    @collections = Collection.active
  end
  
end

app/views/admin/collections/add_products.js.erb
$("#product_name_search").val("");
$("#unassociated_product_ids").html("<%=j options_for_select((Product.all - @collection.products).map { |p| [p.name, p.id] }) %>");
$("#associated_product_ids").html("<%=j options_for_select((@collection.products).map { |p| [p.name, p.id] }) %>");

app/views/admin/collections/edit.html.erb
<%= link_to "All Collections", admin_collections_path %>

<h1>Edit Collection</h1>

<%= form_for [:admin, @collection] do |form| %>

<ul>
	<% @collection.errors.full_messages.each do |error|  %>
		<li><%= error %></li>
	<% end %>
</ul>

<div>
	<%= form.label :name %>
	<%= form.text_field :name %>
</div>

<div>
	<%= form.label :short_description %>
	<%= form.text_area :short_description %>
</div>

<div>
	<%= form.label :long_description %>
	<%= form.text_area :long_description %>
</div>

<div>
	<%= form.radio_button :active, true, checked: form.object.active? %>
	Active
	<%= form.radio_button :active, false, checked: !form.object.active? %>
	Inactive
</div>

<h3>Products</h3>
<div>
	Search Available Products by Name: <%= text_field_tag :product_name_search %>
	<%= link_to "Reset", "#", onclick: "reset_product_search_for_collection(#{@collection.id})" %>
	<%= hidden_field_tag :collection_id, @collection.id %>
</div>

<div class="unassociated_product_ids_div inline_block">
	Available Products:<br>
	<%= select_tag :unassociated_product_ids, options_for_select((Product.all - @collection.products).map { |p| [p.name, p.id] }), {multiple: true, class: "product_multiselect"} %>
</div>

<div class="transfer_product_links inline_block">
	<%= link_to ">", '#', remote: true, onclick: "add_products_to_collection(#{@collection.id})" %><br>
	<%= link_to "<", '#', remote: true, onclick: "remove_products_from_collection(#{@collection.id})" %>
</div>

<div class="associated_product_ids_div inline_block">
	Chosen Products:<br>
	<%= select_tag :associated_product_ids, options_for_select(@collection.products.map { |p| [p.name, p.id] }), {multiple: true, class: "product_multiselect"} %>
</div>

<br>
<%= form.submit %>

<% end %>

<%= link_to "Delete Collection", admin_collection_path(@collection), method: :delete, confirm: "Are you sure?" %>

app/views/admin/collections/index.html.erb
<%= link_to "New Collection", new_admin_collection_path %>

<%= will_paginate @collections %>

<table>
  <thead>
    <th>ID</th>
    <th>Name</th>
  </thead>


  <% @collections.each do |collection| %>
  <tr>
    <td><%= link_to collection.id, edit_admin_collection_path(collection) %></td>
    <td><%= collection.name %></td>
  </tr>
  <% end %>
</table>

app/views/admin/collections/manage_products.html.erb
<%= will_paginate @products %>

<table>
	<thead>
		<th>Name</th>
	</thead>
	
	<% @products.each do |product| %>
	<tr>
		<td class="collection_products_td" id="<%= product.id %>"><%= product.name %></td>
	</tr>
	<% end %>
</table>

app/views/admin/collections/new.html.erb
<%= link_to "All Collections", admin_collections_path %>

<h1>New Collection</h1>

<%= form_for [:admin, @collection] do |form| %>

<ul>
	<% @collection.errors.full_messages.each do |error|  %>
		<li><%= error %></li>
	<% end %>
</ul>

<div>
	<%= form.label :name %>
	<%= form.text_field :name %>
</div>

<div>
	<%= form.label :short_description %>
	<%= form.text_area :short_description %>
</div>

<div>
	<%= form.label :long_description %>
	<%= form.text_area :long_description %>
</div>


<%= form.submit %>

<% end %>

app/views/admin/collections/remove_products.js.erb
$("#product_name_search").val("");
$("#unassociated_product_ids").html("<%=j options_for_select((Product.all - @collection.products).map { |p| [p.name, p.id] }) %>");
$("#associated_product_ids").html("<%=j options_for_select((@collection.products).map { |p| [p.name, p.id] }) %>");

app/views/admin/collections/reset_search.js.erb
$("#product_name_search").val("");
$("#unassociated_product_ids").html("<%=j options_for_select((Product.all - @collection.products).map { |p| [p.name, p.id] }) %>");

app/views/admin/collections/search_products.js.erb
$("#unassociated_product_ids").html("<%=j options_for_select((@products - @collection.products).map { |p| [p.name, p.id] }) %>");